#!/bin/bash

if [ "x$X509_USER_PROXY" = "x" ]; then
    echo "Expecting a X509_USER_PROXY variable to be defined!"
    exit 1
fi

docker inspect occi-voms-proxy &> /dev/null || \
    docker run --name occi-voms-proxy \
        egifedcloud/fedcloud-userinterface \
        /bin/bash -c "(fetch-crl -v -T 30 || true)"

docker run -it --rm --volumes-from occi-voms-proxy \
           -v $PWD:/data:rw -v $X509_USER_PROXY:$X509_USER_PROXY \
           egifedcloud/fedcloud-userinterface \
           occi "$@"
