#!/bin/bash
: ${OCCI_ENDPOINT:="https://carach5.ics.muni.cz:11443"}
: ${VO:=training.egi.eu}
: ${X509_USER_PROXY:=""}


if [ "x$X509_USER_PROXY" = "x" ]; then
    echo "Expecting a X509_USER_PROXY variable to be defined!"
fi

docker inspect occi-voms-proxy &> /dev/null || \
    docker run --name occi-voms-proxy \
        egifedcloud/fedcloud-userinterface \
        /bin/bash -c "(fetch-crl -v -T 30 || true)"

docker run -it --rm --volumes-from occi-voms-proxy \
           -v $PWD:/data:rw -v $X509_USER_PROXY:/tmp/x509up_u0 \
           egifedcloud/fedcloud-userinterface \
           occi -n x509 -x /tmp/x509up_u0 -X -e ${OCCI_ENDPOINT} \
                "$@"
